const assert = require('assert');
const ErrorType = require('../lib/exception.js');

try {
{% for key, value in testData.enumData %}
	assert.strictEqual(ErrorType.{{ key }}, '{{ value }}');
{% endfor %}

	console.log('All tests passed!');
} catch (error) {
	console.error('Test failed:', error);
}
